name: fnb_env
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - configparser

  - pip
  - pip:
    - tqdm
    - glass
    - healpy
    - astropy
    - sbi
    - tarp
    - corner
    - getdist
    - pyccl
    - camb
    - SWIG

# - torch
# - ili
  
